---
database: 
  #connection_string: mysql://root:penguin8@mac-mini.local/braindump
  connection_string: sqlite://database.sqlite3
  log_queries: true
base_url: >
  http://mac-mini.local/~petevilter/svn/braindump/trunk/
enable_mod_rewrite: false
error_reporting: 2